services:
  - type: web
    name: speaker-recognition-api
    env: python
    buildCommand: |
      bash build.sh
      pip install -r requirements.txt
    startCommand: PATH="./bin:$PATH" uvicorn main:app
    plan: free
    autoDeploy: true
